### ISSUE TITLE
failed in  EUROC V1_03_difficult

### ISSUE THREAD

**Issue by nifengzhiyix2** [tum-vision/online_photometric_calibration#10]
hello ,when I run this code for V1_03_difficult in EUROC dataset，
segmentation fault happens.

I run the code by:

./bin/online_pcalib_demo -i '/home/likun/dataset/V1_03_difficult/cam0/data' --image-width 752 --image-height 480

the fault is:

START OPTIMIZATION
image: 1560
image: 1561
image: 1562
image: 1563
image: 1564
END OPTIMIZATION
image: 1565
START OPTIMIZATION
OpenCV Error: Sizes of input arguments do not match (The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array') in arithm_op, file /home/likun/下载/opencv-2.4.13.6/modules/core/src/arithm.cpp, line 1295
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/likun/下载/opencv-2.4.13.6/modules/core/src/arithm.cpp:1295: error: (-209) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function arithm_op

已放弃 (核心已转储)

what can i do ?..........

best regards!

**Comment by NikolausDemmel** [comment]
Does it work for other sequences?

All I can suggest is running it in a debugger and digging into where it fails.

**Comment by nifengzhiyix2** [comment]
it work for most of sequences ,but for some  sequences ,this issue happens.

many thanks! I will debug and try to find reason.

**Comment by nifengzhiyix2** [comment]
It has been solved with the method:
https://github.com/tum-vision/online_photometric_calibration/issues/7
