### ISSUE TITLE
parameter info request

### ISSUE THREAD

**Issue by YibinWu** [tum-vision/online_photometric_calibration#5]
Hi,would you mind showing us the intrinsic parameters(fx,fy,cx,cy and distorted paras and so on) of the camera you used to get the sequence_30 dataset? I am trying to use my own KLT tracks function,and I do need these paras.Thanks!

**Comment by NikolausDemmel** [comment]
Not sure what you mean? We just use the calibration provided with the dataset. Check the camera.txt.

**Comment by NikolausDemmel** [comment]
Not sure what you mean? We don't use any intrinsic calibration in this repository, but the TUMMono dataset includes intrinsic calibration, if you need it. Check the camera.txt files.

**Comment by YibinWu** [comment]
> Not sure what you mean? We don't use any intrinsic calibration in this repository, but the TUMMono dataset includes intrinsic calibration, if you need it. Check the camera.txt files.

Well,I have checked that,but I don't know what these mean.
`0.535719308086809	0.669566858850269	0.493248545285398	0.500408664348414	0.897966326944875
1280 1024
crop
640 480`

**Comment by NikolausDemmel** [comment]
https://github.com/JakobEngel/dso#31-dataset-format

**Comment by YibinWu** [comment]
I get it,thanks!

**Comment by rui2016** [comment]
Hi @Sanduo007, I'm a bit curious why does your KLT tracker need those camera parameters. Would you share the idea with us? Does it help taking them into account?

**Comment by YibinWu** [comment]
@rui2016 
Well,there is nothing special.I just use the parameters to undistort the image and then recover fundamental matrix to eliminate outliers.
