### ISSUE TITLE
There is an interesting question about industrial camera 

### ISSUE THREAD

**Issue by liu657276074** [tum-vision/online_photometric_calibration#8]
Hi ! There is an interesting question about industrial camera.
This method was applied for automatic exposure camera image. Could it be helpful or valid for some industrial camera with manual exposure, which often had fixed exposure time setting during image data acquisition?

**Comment by NikolausDemmel** [comment]
You could still apply the algorithm as is, but if you know the exposure is constant, the algorithm could make use of that and probably give better estimates for vignette and response function.

**Comment by liu657276074** [comment]
Thanks for your explaination! What a promising research you did! :D
